route:
  receiver: dev-webhook
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: dev-webhook
    webhook_configs:
      - url: http://alert-webhook:8080/
        send_resolved: true
